// client-angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title = "Monroe Song List";
}

<nav id="navMain" class="navbar navbar-expand-lg navbar-light sticky-top">
  <div class="container">
    <a class="navbar-brand" href="#">{{title}}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="/songs-list">Songs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" (click)="list.openAddSongModal()">Add Song</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" (click)="list.openAddArtistModal()">Add Artist</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<router-outlet>
</router-outlet>

<nav class="navbar navbar-expand-lg navbar-light fixed-bottom" id="navFooter">
  <div class="container">
    Adam K. Monroe © 2020 - All Rights Reserved
  </div>
</nav>

<app-songs-list #list></app-songs-list>

// client-vue/src/App.vue
<template>
  <b-container>
    <b-navbar toggleable="sm" type="light" variant="light" fixed="top">
      <b-navbar-toggle target="nav-text-collapse"></b-navbar-toggle>

      <b-navbar-brand>Music List</b-navbar-brand>

      <b-collapse id="nav-text-collapse" is-nav>
        <b-navbar-nav>
          <b-nav-item>
            <router-link to="/" tag="li">Home</router-link>
          </b-nav-item>
          <b-nav-item>
            <router-link to="/songs" tag="li">Songs</router-link>
          </b-nav-item>
          <b-nav-item>
            <router-link to="/artists" tag="li">Artists</router-link>
          </b-nav-item>
          <b-nav-item>
            <router-link to tag="li">Add Song</router-link>
          </b-nav-item>
          <b-nav-item>
            <router-link to tag="li">Add Artist</router-link>
          </b-nav-item>
          <b-nav-item>
            <router-link to="/about" tag="li">About</router-link>
          </b-nav-item>
        </b-navbar-nav>
      </b-collapse>
    </b-navbar>

    <router-view />

    <b-navbar type="light" variant="light" fixed="bottom" class="footer"
      >Adam K. Monroe © 2020 - All Rights Reserved</b-navbar
    >
  </b-container>
</template>

<style>
div.container {
  padding-top: 35px;
  padding-bottom: 30px;
}
li {
  text-decoration: none;
}
.footer {
  border-top: rgb(0, 0, 0) 1px solid;
}
</style>
