// client-react/src/components/SongDetails.js
import React from "react";
import { useQuery } from "@apollo/react-hooks";

import { getSongQuery } from "../queries/queries";

function SongDetails(props) {
  const { loading, error, data } = useQuery(getSongQuery, {
    variables: { id: props.song_id },
    skip: props.song_id === null ? true : false
  });

  if (loading)
    return (
      <div id="song-details">
        <p>Loading Details...</p>
      </div>
    );

  if (error) return <p>Something went wrong :(</p>;

  if (props.song_id === null) {
    return (
      <div id="song-details">
        <p>No song selected ...</p>
      </div>
    );
  }

  //const artist_songs = data.song.artist.songs;
  const {
    song: {
      artist: { songs: artist_songs }
    }
  } = data;

  const displayArtistSongs = artist_songs.map(song => (
    <li key={song.id}>{song.title}</li>
  ));

  return (
    <div id="song-details">
      <h3>{data.song.title}</h3>
      <p>Album: {data.song.album}</p>
      <p>Genre: {data.song.genre}</p>
      <p>Artist: {data.song.artist.name}</p>
      <p>Year Started: {data.song.artist.year_started}</p>
      <p>All songs by the artist</p>
      <ul className="artist_songs">{displayArtistSongs}</ul>
    </div>
  );
}

export default SongDetails;

// client-vue/src/components/SongDetails.vue
<template>
  <div>
    <b-overlay :show="$apollo.queries.song.loading" no-wrap></b-overlay>
    <b-card header="Song Details" header-tag="header" :title="song.title">
      <div v-if="song.artist">
        <b-card-text>{{ song.album }}</b-card-text>
        <b-card-text>{{ song.genre }}</b-card-text>
        <b-card-text>{{ song.artist.name }}</b-card-text>
        <br />
        <b-card-text>List of artist's songs</b-card-text>
        <b-list-group>
          <b-list-group-item
            v-for="artist_songs in song.artist.songs"
            :key="artist_songs.id"
          >{{ artist_songs.title }}</b-list-group-item>
        </b-list-group>
        <b-button href="#" variant="primary">Edit</b-button>
        <b-button href="#" variant="danger">Delete</b-button>
      </div>
    </b-card>
  </div>
</template>

<script>
import { getSongQuery } from "../queries/queries.ts";

export default {
  name: "song-details",
  props: {
    songId: String
  },
  data() {
    return {
      song: []
    };
  },
  apollo: {
    song: {
      query: getSongQuery,
      variables() {
        return {
          id: this.songId
        };
      },
      skip() {
        return !this.songId;
      }
    }
  }
};
</script>

<style scoped>
a.btn {
  margin: 0.5rem;
}
</style>
