// client-angular/src/app/components/song-details/song-details.component.ts
import { Component, OnInit, Input, Output } from "@angular/core";
import { EventEmitter } from '@angular/core';

@Component({
  selector: "app-song-details",
  templateUrl: "./song-details.component.html",
  styleUrls: ["./song-details.component.css"]
})
export class SongDetailsComponent implements OnInit {
  @Input() Song: any[] = [];
  @Output("openSongModal") openSongModal:EventEmitter<any> = new EventEmitter();
  
  constructor() {}

  ngOnInit() { }

  openParentModal(){
    this.openSongModal.emit();
  }

}

<div class="card">
  <div class="card-header">
    Song details
  </div>
  <div class="card-body">
    <div *ngIf="Song">
      <h3 class="card-title">{{ Song.title }}</h3>
      <h6 class="card-subtitle mb-2 text-muted">{{ Song.album }}</h6>
      <br />
      <p class="card-text">Genre: <b>{{ Song.genre }}</b></p>
      <p class="card-text">Artist: <b>{{ Song.artist.name }}</b></p>
      <br/>

      <p>List of artist's songs</p>
      <ul class="list-group list-group-flush">
        <li class="list-group-item" *ngFor="let artist_song of Song.artist.songs">{{artist_song.title}}</li>
      </ul>
    </div>
    <div class="detail-buttons" *ngIf="Song">
      <button class="btn btn-info" (click)="openParentModal()">Edit</button>
      &nbsp;
      <button class="btn btn-danger">Delete</button>
    </div>
  </div>
</div>

// client-vue/src/components/SongDetails.vue
<template>
  <div>
    <b-overlay :show="$apollo.queries.song.loading" no-wrap></b-overlay>
    <b-card header="Song Details" header-tag="header" :title="song.title">
      <div v-if="song.artist">
        <b-card-text>{{ song.album }}</b-card-text>
        <b-card-text>{{ song.genre }}</b-card-text>
        <b-card-text>{{ song.artist.name }}</b-card-text>
        <br />
        <b-card-text>List of artist's songs</b-card-text>
        <b-list-group>
          <b-list-group-item
            v-for="artist_songs in song.artist.songs"
            :key="artist_songs.id"
          >{{ artist_songs.title }}</b-list-group-item>
        </b-list-group>
        <b-button href="#" variant="primary">Edit</b-button>
        <b-button href="#" variant="danger">Delete</b-button>
      </div>
    </b-card>
  </div>
</template>

<script>
import { getSongQuery } from "../queries/queries.ts";

export default {
  name: "song-details",
  props: {
    songId: String
  },
  data() {
    return {
      song: []
    };
  },
  apollo: {
    song: {
      query: getSongQuery,
      variables() {
        return {
          id: this.songId
        };
      },
      skip() {
        return !this.songId;
      }
    }
  }
};
</script>

<style scoped>
a.btn {
  margin: 0.5rem;
}
</style>
